jobs:
  assign-reviewers:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: trask/component-owners@main
      with:
        assign-owners: false
name: Assign reviewers
on:
  repository_dispatch:
    types: trigger-ga___assign-reviewers.yml
