jobs:
  check-versions:
    outputs:
      already-opened: ${{ steps.check-versions.outputs.already-opened }}
      current-version: ${{ steps.check-versions.outputs.current-version }}
      latest-version: ${{ steps.check-versions.outputs.latest-version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: check-versions
      name: Check versions
      run: "current_version=$(grep -Po \"val otelSdkVersion = \\\"\\K[0-9]+.[0-9]+.[0-9]+\"\
        \ \\\n                      dependencyManagement/build.gradle.kts)\nlatest_version=$(gh\
        \ release view \\\n                     --repo open-telemetry/opentelemetry-java\
        \ \\\n                     --json tagName \\\n                     --jq .tagName\
        \ \\\n                   | sed 's/^v//')\n\nmatches=$(gh pr list \\\n    \
        \          --author opentelemetrybot \\\n              --state open \\\n \
        \             --search \"in:title \\\"Update the OpenTelemetry SDK version\
        \ to $latest_version\\\"\")\nif [ ! -z \"$matches\" ]\nthen\n  already_opened=true\n\
        fi\n\necho \"current-version=$current_version\" >> $GITHUB_OUTPUT\necho \"\
        latest-version=$latest_version\" >> $GITHUB_OUTPUT\necho \"already-opened=$already_opened\"\
        \ >> $GITHUB_OUTPUT\n"
  update-otel-sdk:
    if: 'needs.check-versions.outputs.current-version != needs.check-versions.outputs.latest-version
      &&

      needs.check-versions.outputs.already-opened != ''true''

      '
    needs:
    - check-versions
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      env:
        VERSION: ${{ needs.check-versions.outputs.latest-version }}
      name: Update version
      run: ./.github/scripts/update-sdk-version.sh $VERSION
    - continue-on-error: true
      name: Use CLA approved github bot
      run: .github/scripts/use-cla-approved-github-bot.sh
    - continue-on-error: true
      name: Free disk space
      run: .github/scripts/gha-free-disk-space.sh
    - continue-on-error: true
      name: Set up JDK for running Gradle
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 17.0.6
    - continue-on-error: true
      name: Update license report
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        arguments: generateLicenseReport
    - continue-on-error: true
      if: failure()
      name: Undo license report clean
      run: git checkout -- licenses
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
        VERSION: ${{ needs.check-versions.outputs.latest-version }}
      if: success() || failure()
      name: Create pull request against main
      run: "message=\"Update the OpenTelemetry SDK version to $VERSION\"\nbody=\"\
        Update the OpenTelemetry SDK version to \\`$VERSION\\`.\"\nbranch=\"opentelemetrybot/update-opentelemetry-sdk-to-${VERSION}\"\
        \n\ngit checkout -b $branch\ngit add -u\ngit add licenses\ngit commit -m \"\
        $message\"\ngit push --set-upstream origin $branch\ngh pr create --title \"\
        $message\" \\\n             --body \"$body\" \\\n             --base main\n"
name: Auto-update OpenTelemetry SDK
on:
  repository_dispatch:
    types: trigger-ga___auto-update-otel-sdk.yml
