jobs:
  backport:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: "if [[ ! $GITHUB_REF_NAME =~ ^release/v[0-9]+\\.[0-9]+\\.x$ ]]; then\n\
        \  echo this workflow should only be run against release branches\n  exit\
        \ 1\nfi\n"
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Use CLA approved github bot
      run: .github/scripts/use-cla-approved-github-bot.sh
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
        NUMBER: ${{ github.event.inputs.number }}
      name: Create pull request
      run: "commit=$(gh pr view $NUMBER --json mergeCommit --jq .mergeCommit.oid)\n\
        title=$(gh pr view $NUMBER --json title --jq .title)\n\nbranch=\"opentelemetrybot/backport-${NUMBER}-to-${GITHUB_REF_NAME//\\\
        //-}\"\n\ngit checkout -b $branch\ngit cherry-pick $commit\ngit push --set-upstream\
        \ origin $branch\ngh pr create --title \"[$GITHUB_REF_NAME] $title\" \\\n\
        \             --body \"Clean cherry-pick of #$NUMBER to the \\`$GITHUB_REF_NAME\\\
        ` branch.\" \\\n             --base $GITHUB_REF_NAME\n"
name: Backport
on:
  repository_dispatch:
    types: trigger-ga___backport.yml
permissions:
  contents: read
