jobs:
  common:
    secrets:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
    uses: ./.github/workflows/build-common.yml
  markdown-link-check:
    if: '!startsWith(github.ref_name, ''release/'')'
    uses: ./.github/workflows/reusable-markdown-link-check.yml
  markdown-lint-check:
    if: '!startsWith(github.ref_name, ''release/'')'
    uses: ./.github/workflows/reusable-markdown-lint-check.yml
  misspell-check:
    if: '!startsWith(github.ref_name, ''release/'')'
    uses: ./.github/workflows/reusable-misspell-check.yml
  muzzle:
    if: '!startsWith(github.ref_name, ''release/'')'
    uses: ./.github/workflows/reusable-muzzle.yml
  publish-snapshots:
    if: github.ref_name == 'main' && github.repository == 'open-telemetry/opentelemetry-java-instrumentation'
    needs:
    - common
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Free disk space
      run: .github/scripts/gha-free-disk-space.sh
    - continue-on-error: true
      name: Set up JDK for running Gradle
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 17.0.6
    - continue-on-error: true
      env:
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      name: Build and publish artifact snapshots
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        arguments: assemble publishToSonatype
        gradle-home-cache-excludes: caches/build-cache-1
    - continue-on-error: true
      env:
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      name: Build and publish gradle plugin snapshots
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        arguments: build publishToSonatype
        build-root-directory: gradle-plugins
        gradle-home-cache-excludes: caches/build-cache-1
  shell-script-check:
    if: '!startsWith(github.ref_name, ''release/'')'
    uses: ./.github/workflows/reusable-shell-script-check.yml
  test-latest-deps:
    if: '!startsWith(github.ref_name, ''release/'')'
    secrets:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
    uses: ./.github/workflows/reusable-test-latest-deps.yml
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
