jobs:
  common:
    secrets:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
    uses: ./.github/workflows/build-common.yml
  markdown-link-check:
    uses: ./.github/workflows/reusable-markdown-link-check.yml
  markdown-lint-check:
    uses: ./.github/workflows/reusable-markdown-lint-check.yml
  misspell-check:
    uses: ./.github/workflows/reusable-misspell-check.yml
  muzzle:
    uses: ./.github/workflows/reusable-muzzle.yml
  shell-script-check:
    uses: ./.github/workflows/reusable-shell-script-check.yml
  test-latest-deps:
    secrets:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
    uses: ./.github/workflows/reusable-test-latest-deps.yml
  workflow-notification:
    if: always()
    needs:
    - common
    - test-latest-deps
    - muzzle
    - markdown-link-check
    - misspell-check
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: "${{\n  needs.common.result == 'success' &&\n  needs.test-latest-deps.result\
        \ == 'success' &&\n  needs.muzzle.result == 'success' &&\n  needs.markdown-link-check.result\
        \ == 'success' &&\n  needs.misspell-check.result == 'success'\n}}"
name: Build (daily)
on:
  repository_dispatch:
    types: trigger-ga___build-daily.yml
