concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
jobs:
  common:
    uses: ./.github/workflows/build-common.yml
    with:
      cache-read-only: true
      skip-openj9-tests: ${{ !contains(github.event.pull_request.labels.*.name, 'test
        openj9') }}
      skip-windows-smoke-tests: ${{ !contains(github.event.pull_request.labels.*.name,
        'test windows') }}
  markdown-link-check:
    if: '!startsWith(github.ref_name, ''release/'') && !startsWith(github.base_ref,
      ''release/'')'
    uses: ./.github/workflows/reusable-markdown-link-check.yml
  markdown-lint-check:
    uses: ./.github/workflows/reusable-markdown-lint-check.yml
  misspell-check:
    uses: ./.github/workflows/reusable-misspell-check.yml
  muzzle:
    uses: ./.github/workflows/reusable-muzzle.yml
    with:
      cache-read-only: true
  required-status-check:
    if: always()
    needs:
    - common
    - muzzle
    - shell-script-check
    - markdown-lint-check
    - misspell-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: "needs.common.result != 'success' ||\n(\n  !startsWith(github.base_ref,\
        \ 'release/') &&\n  (\n    needs.muzzle.result != 'success' ||\n    needs.shell-script-check.result\
        \ != 'success' ||\n    needs.markdown-lint-check.result != 'success' ||\n\
        \    needs.misspell-check.result != 'success'\n  )\n)\n"
      run: exit 1
  shell-script-check:
    uses: ./.github/workflows/reusable-shell-script-check.yml
  test-indy:
    uses: ./.github/workflows/reusable-test-indy.yml
    with:
      cache-read-only: true
  test-latest-deps:
    uses: ./.github/workflows/reusable-test-latest-deps.yml
    with:
      cache-read-only: true
  test-native:
    uses: ./.github/workflows/reusable-native-tests.yml
    with:
      skip-native-tests: ${{ !contains(github.event.pull_request.labels.*.name, 'test
        native') }}
name: Build pull request
on:
  repository_dispatch:
    types: trigger-ga___build-pull-request.yml
