jobs:
  common:
    secrets:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
    uses: ./.github/workflows/build-common.yml
    with:
      no-build-cache: true
  test-latest-deps:
    secrets:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
    uses: ./.github/workflows/reusable-test-latest-deps.yml
    with:
      no-build-cache: true
  workflow-notification:
    if: always()
    needs:
    - common
    - test-latest-deps
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: "${{\n  needs.common.result == 'success' &&\n  needs.test-latest-deps.result\
        \ == 'success'\n}}"
name: Build (daily --no-build-cache)
on:
  repository_dispatch:
    types: trigger-ga___build-daily-no-build-cache.yml
