jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e
      with:
        days-before-close: 7
        days-before-stale: 7
        only-labels: needs author feedback
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: stale
        stale-issue-message: 'This has been automatically marked as stale because
          it has been marked as needing author feedback and has not had any activity
          for 7 days. It will be closed automatically if there is no response from
          the author within 7 additional days from this comment.

          '
        stale-pr-label: stale
        stale-pr-message: 'This has been automatically marked as stale because it
          has been marked as needing author feedback and has not had any activity
          for 7 days. It will be closed automatically if there is no response from
          the author within 7 additional days from this comment.

          '
name: Issue management - run stale action
on:
  repository_dispatch:
    types: trigger-ga___issue-management-stale-action.yml
permissions:
  contents: read
