jobs:
  graalvm-native-tests:
    uses: ./.github/workflows/reusable-native-tests.yml
  workflow-notification:
    if: always()
    needs:
    - graalvm-native-tests
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.graalvm-native-tests.result == 'success' }}
name: Daily GraalVM native tests
on:
  repository_dispatch:
    types: trigger-ga___native-tests-daily.yml
