jobs:
  run-overhead-tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        path: gh-pages
        ref: gh-pages
    - continue-on-error: true
      name: Free disk space
      run: .github/scripts/gha-free-disk-space.sh
    - continue-on-error: true
      name: Copy results from gh-pages branch
      run: 'rsync -avv gh-pages/benchmark-overhead/results/ benchmark-overhead/results/

        '
    - continue-on-error: true
      name: Run tests
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        arguments: test
        build-root-directory: benchmark-overhead
    - continue-on-error: true
      name: Inspect the results dir
      run: ls -lR results
      working-directory: benchmark-overhead
    - continue-on-error: true
      name: Copy results back to gh-pages branch
      run: rsync -avv benchmark-overhead/results/ gh-pages/benchmark-overhead/results/
        && rm -rf benchmark-overhead/results
    - continue-on-error: true
      name: Commit updated results
      uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5
      with:
        add: benchmark-overhead/results
        author_email: 107717825+opentelemetrybot@users.noreply.github.com
        author_name: opentelemetrybot
        branch: gh-pages
        committer_email: 107717825+opentelemetrybot@users.noreply.github.com
        committer_name: opentelemetrybot
        cwd: ./gh-pages
        message: update test result data
  workflow-notification:
    if: always()
    needs:
    - run-overhead-tests
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.run-overhead-tests.result == 'success' }}
name: Overhead benchmark (daily)
on:
  repository_dispatch:
    types: trigger-ga___overhead-benchmark-daily.yml
