jobs:
  analyze:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Free disk space
      run: .github/scripts/gha-free-disk-space.sh
    - continue-on-error: true
      name: Set up JDK for running Gradle
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 17.0.6
    - continue-on-error: true
      name: Increase gradle daemon heap size
      run: 'sed -i "s/org.gradle.jvmargs=/org.gradle.jvmargs=-Xmx3g /" gradle.properties

        '
    - continue-on-error: true
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        arguments: :javaagent:dependencyCheckAnalyze
    - continue-on-error: true
      if: always()
      name: Upload report
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        path: javaagent/build/reports
  workflow-notification:
    if: always()
    needs:
    - analyze
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.analyze.result == 'success' }}
name: OWASP dependency check (daily)
on:
  repository_dispatch:
    types: trigger-ga___owasp-dependency-check-daily.yml
