jobs:
  buildLinux:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Free disk space
      run: .github/scripts/gha-free-disk-space.sh
    - continue-on-error: true
      name: Set up JDK for running Gradle
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 17.0.6
    - continue-on-error: true
      name: Build Docker image
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        arguments: :smoke-tests:images:fake-backend:jibDockerBuild -Djib.httpTimeout=120000
          -Djib.console=plain
        cache-read-only: true
        gradle-home-cache-excludes: caches/build-cache-1
  buildWindows:
    defaults:
      run:
        shell: bash
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Support long paths
      run: git config --system core.longpaths true
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Set up JDK for running Gradle
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 17.0.6
    - continue-on-error: true
      name: Build Docker image
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        arguments: :smoke-tests:images:fake-backend:windowsBackendImageBuild
        cache-read-only: true
name: PR build fake backend images for smoke tests
on:
  repository_dispatch:
    types: trigger-ga___pr-smoke-test-fake-backend-images.yml
permissions:
  contents: read
