jobs:
  build:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      cache-read-only: true
      project: :smoke-tests:images:play
      skip-java-17: true
      skip-java-21: true
name: PR build Play images for smoke tests
on:
  repository_dispatch:
    types: trigger-ga___pr-smoke-test-play-images.yml
