jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: matrix.os == 'windows-latest'
      name: Support long paths
      run: git config --system core.longpaths true
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Free disk space
      run: .github/scripts/gha-free-disk-space.sh
    - continue-on-error: true
      name: Set up JDK for running Gradle
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17.0.6
    - continue-on-error: true
      name: Set up Gradle cache
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        cache-read-only: true
    - continue-on-error: true
      if: matrix.os != 'windows-latest'
      name: Build Linux docker images
      run: ./gradlew :smoke-tests:images:servlet:buildLinuxTestImages -PsmokeTestServer=${{
        matrix.smoke-test-server }}
    - continue-on-error: true
      if: matrix.os == 'windows-latest'
      name: Build Windows docker images
      run: ./gradlew :smoke-tests:images:servlet:buildWindowsTestImages -PsmokeTestServer=${{
        matrix.smoke-test-server }}
    strategy:
      fail-fast: false
      matrix:
        exclude:
        - os: windows-latest
          smoke-test-server: websphere
        os:
        - windows-latest
        - ubuntu-latest
        smoke-test-server:
        - jetty
        - liberty
        - payara
        - tomcat
        - tomee
        - websphere
        - wildfly
name: PR build Servlet images for smoke tests
on:
  repository_dispatch:
    types: trigger-ga___pr-smoke-test-servlet-images.yml
