jobs:
  build:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      cache-read-only: true
      project: :smoke-tests:images:grpc
name: PR build gRPC images for smoke tests
on:
  repository_dispatch:
    types: trigger-ga___pr-smoke-test-grpc-images.yml
