jobs:
  build:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      cache-read-only: true
      project: :smoke-tests:images:quarkus
      skip-java-8: true
name: PR build Quarkus images for smoke tests
on:
  repository_dispatch:
    types: trigger-ga___pr-smoke-test-quarkus-images.yml
