jobs:
  publish:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      project: :smoke-tests:images:security-manager
      publish: true
  workflow-notification:
    if: always()
    needs:
    - publish
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.publish.result == 'success' }}
name: Publish Security Manager test app images for smoke tests
on:
  repository_dispatch:
    types: trigger-ga___publish-smoke-test-security-manager-images.yml
