jobs:
  publish:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      project: :smoke-tests:images:quarkus
      publish: true
      skip-java-8: true
  workflow-notification:
    if: always()
    needs:
    - publish
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.publish.result == 'success' }}
name: Publish Quarkus images for smoke tests
on:
  repository_dispatch:
    types: trigger-ga___publish-smoke-test-quarkus-images.yml
