jobs:
  prepare:
    outputs:
      tag: ${{ steps.set-tag.outputs.TAG }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: set-tag
      name: Set tag
      run: echo "TAG=$(date '+%Y%m%d').$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
  publish:
    defaults:
      run:
        shell: bash
    needs: prepare
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: matrix.os == 'windows-latest'
      name: Support long paths
      run: git config --system core.longpaths true
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      if: matrix.os != 'windows-latest'
      name: Free disk space
      run: .github/scripts/gha-free-disk-space.sh
    - continue-on-error: true
      name: Set up JDK for running Gradle
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 17.0.6
    - continue-on-error: true
      name: Login to GitHub package registry
      uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - continue-on-error: true
      name: Set up Gradle cache
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        cache-read-only: ${{ matrix.smoke-test-suite != 'tomcat' }}
    - continue-on-error: true
      if: matrix.os != 'windows-latest'
      name: Build Linux docker images
      run: ./gradlew :smoke-tests:images:servlet:buildLinuxTestImages pushMatrix -PextraTag=${{
        needs.prepare.outputs.tag }} -PsmokeTestServer=${{ matrix.smoke-test-server
        }}
    - continue-on-error: true
      if: matrix.os == 'windows-latest'
      name: Build Windows docker images
      run: ./gradlew :smoke-tests:images:servlet:buildWindowsTestImages pushMatrix
        -PextraTag=${{ needs.prepare.outputs.tag }} -PsmokeTestServer=${{ matrix.smoke-test-server
        }}
    strategy:
      fail-fast: false
      matrix:
        exclude:
        - os: windows-latest
          smoke-test-server: websphere
        os:
        - windows-latest
        - ubuntu-latest
        smoke-test-server:
        - jetty
        - liberty
        - payara
        - tomcat
        - tomee
        - websphere
        - wildfly
  workflow-notification:
    if: always()
    needs:
    - publish
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.publish.result == 'success' }}
name: Publish Servlet images for smoke tests
on:
  repository_dispatch:
    types: trigger-ga___publish-smoke-test-servlet-images.yml
