jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: docker/setup-buildx-action@v3
    - continue-on-error: true
      name: Login to GitHub container registry
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - continue-on-error: true
      name: Create timestamp for docker image tag
      run: echo "TS=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
    - continue-on-error: true
      name: Push to GitHub packages
      uses: docker/build-push-action@v5
      with:
        file: benchmark-overhead/Dockerfile-petclinic-base
        push: false
        tags: ghcr.io/open-telemetry/opentelemetry-java-instrumentation/petclinic-rest-base:${{
          env.TS }}
name: Publish PetClinic benchmark image
on:
  repository_dispatch:
    types: trigger-ga___publish-petclinic-benchmark-image.yml
