jobs:
  merge-change-log-to-main:
    needs:
    - release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      env:
        VERSION: ${{ needs.release.outputs.version }}
      name: Copy change log section from release branch
      run: "sed -n \"0,/^## Version $VERSION /d;/^## Version /q;p\" CHANGELOG.md \\\
        \n  > /tmp/changelog-section.md\n"
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        ref: main
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ needs.release.outputs.version }}
      name: Merge change log to main
      run: 'release_date=$(gh release view v$VERSION --json publishedAt --jq .publishedAt
        | sed ''s/T.*//'')

        RELEASE_DATE=$release_date .github/scripts/merge-change-log-after-release.sh

        '
    - continue-on-error: true
      name: Use CLA approved github bot
      run: .github/scripts/use-cla-approved-github-bot.sh
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
        VERSION: ${{ needs.release.outputs.version }}
      name: Create pull request against main
      run: "if git diff --quiet; then\n  if [[ $VERSION == *.0 ]]; then\n    echo\
        \ there are no updates to merge, not creating pull request\n    exit 0 # success\n\
        \  else\n    echo patch release notes did not get applied for some reason\n\
        \    exit 1 # failure\n  fi\nfi\n\nmessage=\"Merge change log updates from\
        \ $GITHUB_REF_NAME\"\nbody=\"Merge change log updates from \\`$GITHUB_REF_NAME\\\
        `.\"\nbranch=\"opentelemetrybot/merge-change-log-updates-from-${GITHUB_REF_NAME//\\\
        //-}\"\n\ngit checkout -b $branch\ngit commit -a -m \"$message\"\ngit push\
        \ --set-upstream origin $branch\ngh pr create --title \"$message\" \\\n  \
        \           --body \"$body\" \\\n             --base main\n"
  release:
    needs:
    - required-jobs
    outputs:
      version: ${{ steps.create-github-release.outputs.version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: "if [[ $GITHUB_REF_NAME != release/* ]]; then\n  echo this workflow should\
        \ only be run against release branches\n  exit 1\nfi\n"
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Set environment variables
      run: "version=$(.github/scripts/get-version.sh)\nif [[ $version =~ ^([0-9]+)\\\
        .([0-9]+)\\.([0-9]+) ]]; then\n  major=\"${BASH_REMATCH[1]}\"\n  minor=\"\
        ${BASH_REMATCH[2]}\"\n  patch=\"${BASH_REMATCH[3]}\"\nelse\n  echo \"unexpected\
        \ version: $version\"\n  exit 1\nfi\nif [[ $patch == 0 ]]; then\n  if [[ $minor\
        \ == 0 ]]; then\n    prior_major=$((major - 1))\n    prior_minor=$(grep -Po\
        \ \"^## Version $prior_major.\\K[0-9]+\" CHANGELOG.md | head -1)\n    prior_version=\"\
        $prior_major.$prior_minor\"\n  else\n    prior_version=\"$major.$((minor -\
        \ 1)).0\"\n  fi\nelse\n  prior_version=\"$major.$minor.$((patch - 1))\"\n\
        fi\necho \"VERSION=$version\" >> $GITHUB_ENV\necho \"PRIOR_VERSION=$prior_version\"\
        \ >> $GITHUB_ENV\n"
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        ref: main
    - continue-on-error: true
      name: Check that change log update was merged to main
      run: "if [[ $VERSION == *.0 ]]; then\n  # not making a patch release\n  if !\
        \ grep --quiet \"^## Version $VERSION \" CHANGELOG.md; then\n    echo the\
        \ pull request generated by prepare-release-branch.yml needs to be merged\
        \ first\n    exit 1\n  fi\nfi\n"
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Free disk space
      run: .github/scripts/gha-free-disk-space.sh
    - continue-on-error: true
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 17.0.6
    - continue-on-error: true
      env:
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      name: Build and publish artifacts
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        arguments: assemble publishToSonatype closeAndReleaseSonatypeStagingRepository
    - continue-on-error: true
      env:
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      name: Build and publish gradle plugins
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        arguments: build publishPlugins publishPluginMavenPublicationToSonatypeRepository
          closeAndReleaseSonatypeStagingRepository
        build-root-directory: gradle-plugins
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Generate release notes
      run: "sdk_version=$(grep -Po \"val otelSdkVersion = \\\"\\K[0-9]+.[0-9]+.[0-9]+\"\
        \ dependencyManagement/build.gradle.kts)\n\n# conditional blocks not indented\
        \ because of the heredoc\nif [[ $VERSION == *.0 ]]; then\ncat > /tmp/release-notes.txt\
        \ << EOF\nThis release targets the OpenTelemetry SDK $sdk_version.\n\nNote\
        \ that many artifacts have the \\`-alpha\\` suffix attached to their version\
        \ number, reflecting that they are still alpha quality and will continue to\
        \ have breaking changes. Please see the [VERSIONING.md](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/VERSIONING.md#opentelemetry-java-instrumentation-versioning)\
        \ for more details.\n\nEOF\nelse\ncat > /tmp/release-notes.txt << EOF\nThis\
        \ is a patch release on the previous $PRIOR_VERSION release, fixing the issue(s)\
        \ below.\n\nEOF\nfi\n\n# CHANGELOG_SECTION.md is also used at the end of the\
        \ release workflow\n# for copying the change log updates to main\nsed -n \"\
        0,/^## Version $VERSION /d;/^## Version /q;p\" CHANGELOG.md \\\n  > /tmp/CHANGELOG_SECTION.md\n\
        \n# the complex perl regex is needed because markdown docs render newlines\
        \ as soft wraps\n# while release notes render them as line breaks\nperl -0pe\
        \ 's/(?<!\\n)\\n *(?!\\n)(?![-*] )(?![1-9]+\\. )/ /g' /tmp/CHANGELOG_SECTION.md\
        \ \\\n  >> /tmp/release-notes.txt\n\n# conditional block not indented because\
        \ of the heredoc\nif [[ $VERSION == *.0 ]]; then\ncat >> /tmp/release-notes.txt\
        \ << EOF\n### \U0001F647 Thank you\n\nThis release was possible thanks to\
        \ the following contributors who shared their brilliant ideas and awesome\
        \ pull requests:\n\nEOF\n\n.github/scripts/generate-release-contributors.sh\
        \ v$PRIOR_VERSION >> /tmp/release-notes.txt\nfi\n"
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create-github-release
      name: Create GitHub release
      run: "cp javaagent/build/libs/opentelemetry-javaagent-${VERSION}.jar opentelemetry-javaagent.jar\n\
        gh release create --target $GITHUB_REF_NAME \\\n                  --title\
        \ \"Version $VERSION\" \\\n                  --notes-file /tmp/release-notes.txt\
        \ \\\n                  v$VERSION \\\n                  opentelemetry-javaagent.jar\n\
        \necho \"version=$VERSION\" >> $GITHUB_OUTPUT\n"
  required-jobs:
    uses: ./.github/workflows/build-common.yml
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
