jobs:
  misspell-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Install misspell
      run: "curl -L -o install-misspell.sh \\\n     https://raw.githubusercontent.com/client9/misspell/master/install-misspell.sh\n\
        sh ./install-misspell.sh\n"
    - continue-on-error: true
      name: Run misspell
      run: "find . -type f \\\n       -not -path './licenses/*' \\\n     | xargs bin/misspell\
        \ -error\n"
name: Reusable - Misspell check
on:
  repository_dispatch:
    types: trigger-ga___reusable-misspell-check.yml
permissions:
  contents: read
