jobs:
  test-latest-deps:
    name: testLatestDeps${{ matrix.test-partition }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Free disk space
      run: .github/scripts/gha-free-disk-space.sh
    - continue-on-error: true
      name: Set up JDK for running Gradle
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 17.0.6
    - continue-on-error: true
      name: Increase gradle daemon heap size
      run: 'sed -i "s/org.gradle.jvmargs=/org.gradle.jvmargs=-Xmx3g /" gradle.properties

        '
    - continue-on-error: true
      name: Cache pnpm modules
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        key: ${{ runner.os }}-test-latest-cache-pnpm-modules
        path: ~/.pnpm-store
    - continue-on-error: true
      name: Start deadlock detector
      run: .github/scripts/deadlock-detector.sh
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      name: List tests
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        arguments: 'check -x spotlessCheck listTestsInPartition -PtestPartition=${{
          matrix.test-partition }} -PtestLatestDeps=true

          '
        cache-read-only: true
    - continue-on-error: true
      name: Set test tasks
      run: 'echo "test-tasks=$(cat test-tasks.txt | xargs echo | sed ''s/\n/ /g'')"
        >> $GITHUB_ENV

        '
    - continue-on-error: true
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      name: Test
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        arguments: '${{ env.test-tasks }} -PtestLatestDeps=true ${{ inputs.no-build-cache
          && '' --no-build-cache'' || '''' }}

          '
        cache-read-only: ${{ inputs.cache-read-only }}
        gradle-home-cache-excludes: caches/build-cache-1
    - continue-on-error: true
      if: ${{ !cancelled() && hashFiles('build-scan.txt') != '' }}
      name: Build scan
      run: cat build-scan.txt
    - continue-on-error: true
      if: failure()
      name: Upload deadlock detector artifacts if any
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        if-no-files-found: ignore
        name: deadlock-detector-test-latest-${{ matrix.test-java-version }}-${{ matrix.vm
          }}-${{ matrix.test-partition }}
        path: /tmp/deadlock-detector-*
    - continue-on-error: true
      if: failure()
      name: Upload jvm crash dump files if any
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        if-no-files-found: ignore
        name: javacore-test-latest-${{ matrix.test-java-version }}-${{ matrix.test-partition
          }}
        path: '**/hs_err_pid*.log

          **/javacore.*.txt

          **/Snap.*.trc

          **/core.*.dmp

          **/jitdump.*.dmp

          '
    strategy:
      fail-fast: false
      matrix:
        test-partition:
        - 0
        - 1
        - 2
        - 3
name: Reusable - Test latest deps
on:
  repository_dispatch:
    types: trigger-ga___reusable-test-latest-deps.yml
permissions:
  contents: read
