jobs:
  markdown-link-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Install markdown-link-check
      run: npm install -g markdown-link-check@3.11.2
    - continue-on-error: true
      name: Run markdown-link-check
      run: "find . -type f \\\n       -name '*.md' \\\n       -not -path './CHANGELOG.md'\
        \ \\\n       -not -path './licenses/*' \\\n       -not -path '*/build/*' \\\
        \n     | xargs .github/scripts/markdown-link-check-with-retry.sh\n"
name: Reusable - Markdown link check
on:
  repository_dispatch:
    types: trigger-ga___reusable-markdown-link-check.yml
permissions:
  contents: read
