jobs:
  muzzle:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Free disk space
      run: .github/scripts/gha-free-disk-space.sh
    - continue-on-error: true
      name: Set up JDK for running Gradle
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 17.0.6
    - continue-on-error: true
      name: Run muzzle
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        arguments: ${{ matrix.task }}
        cache-read-only: ${{ inputs.cache-read-only }}
    strategy:
      fail-fast: false
      matrix:
        task:
        - :instrumentation:muzzle1
        - :instrumentation:muzzle2
        - :instrumentation:muzzle3
        - :instrumentation:muzzle4
name: Reusable - Muzzle
on:
  repository_dispatch:
    types: trigger-ga___reusable-muzzle.yml
permissions:
  contents: read
