jobs:
  workflow-notification:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Open issue or add comment if issue already open
      run: "# TODO (trask) search doesn't support exact phrases, so it's possible\
        \ that this could grab the wrong issue\nnumber=$(gh issue list --search \"\
        in:title Workflow failed: $GITHUB_WORKFLOW\" --limit 1 --json number -q .[].number)\n\
        \necho $number\necho ${{ inputs.success }}\n\nif [[ $number ]]; then\n  if\
        \ [[ \"${{ inputs.success }}\" == \"true\" ]]; then\n    gh issue close $number\n\
        \  else\n    gh issue comment $number \\\n                     --body \"See\
        \ [$GITHUB_WORKFLOW #$GITHUB_RUN_NUMBER](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID).\"\
        \n  fi\nelif [[ \"${{ inputs.success }}\" == \"false\" ]]; then\n  gh issue\
        \ create --title \"Workflow failed: $GITHUB_WORKFLOW (#$GITHUB_RUN_NUMBER)\"\
        \ \\\n                  --body \"See [$GITHUB_WORKFLOW #$GITHUB_RUN_NUMBER](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID).\"\
        \nfi\n"
name: Reusable - Workflow notification
on:
  repository_dispatch:
    types: trigger-ga___reusable-workflow-notification.yml
