jobs:
  markdown-lint-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Install mardkdownlint
      run: npm install -g markdownlint-cli
    - continue-on-error: true
      name: Run markdownlint
      run: 'markdownlint -c .markdownlint.yml -p .gitignore **/*.md -i licenses/licenses.md

        '
name: Reusable - Markdown lint check
on:
  repository_dispatch:
    types: trigger-ga___reusable-markdown-lint-check.yml
permissions:
  contents: read
