jobs:
  build:
    permissions:
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Free disk space
      run: .github/scripts/gha-free-disk-space.sh
    - continue-on-error: true
      name: Set up JDK for running Gradle
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 17.0.6
    - continue-on-error: true
      if: inputs.publish
      name: Login to GitHub package registry
      uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - continue-on-error: true
      name: Set tag
      run: echo "TAG=$(date '+%Y%m%d').$GITHUB_RUN_ID" >> $GITHUB_ENV
    - continue-on-error: true
      name: Set up Gradle cache
      uses: gradle/actions/setup-gradle@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11
      with:
        cache-read-only: ${{ inputs.cache-read-only }}
    - continue-on-error: true
      if: '!inputs.skip-java-8'
      name: Build Java 8 Docker image
      run: ./gradlew ${{ inputs.project }}:${{ inputs.publish && 'jib' || 'jibDockerBuild'
        }} -Ptag=${{ env.TAG }} -PtargetJDK=8 -Djib.httpTimeout=120000 -Djib.console=plain
    - continue-on-error: true
      name: Build Java 11 Docker image
      run: ./gradlew ${{ inputs.project }}:${{ inputs.publish && 'jib' || 'jibDockerBuild'
        }} -Ptag=${{ env.TAG }} -PtargetJDK=11 -Djib.httpTimeout=120000 -Djib.console=plain
    - continue-on-error: true
      if: '!inputs.skip-java-17'
      name: Build Java 17 Docker image
      run: ./gradlew ${{ inputs.project }}:${{ inputs.publish && 'jib' || 'jibDockerBuild'
        }} -Ptag=${{ env.TAG }} -PtargetJDK=17 -Djib.httpTimeout=120000 -Djib.console=plain
    - continue-on-error: true
      if: '!inputs.skip-java-21'
      name: Build Java 21 Docker image
      run: ./gradlew ${{ inputs.project }}:${{ inputs.publish && 'jib' || 'jibDockerBuild'
        }} -Ptag=${{ env.TAG }} -PtargetJDK=21 -Djib.httpTimeout=120000 -Djib.console=plain
name: PR build fake backend images for smoke tests
on:
  repository_dispatch:
    types: trigger-ga___reusable-smoke-test-images.yml
permissions:
  contents: read
