jobs:
  graalvm-native-tests:
    if: '!inputs.skip-native-tests'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      uses: graalvm/setup-graalvm@2f25c0caae5b220866f732832d5e3e29ff493338
      with:
        components: native-image
        java-version: '17'
        version: latest
    - continue-on-error: true
      name: Running test
      run: 'echo "GRAALVM_HOME: $GRAALVM_HOME"

        echo "JAVA_HOME: $JAVA_HOME"

        java --version

        gu --version

        native-image --version

        ./gradlew nativeTest

        '
name: Reusable - Native tests
on:
  repository_dispatch:
    types: trigger-ga___reusable-native-tests.yml
