jobs:
  shell-script-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Install shell check
      run: wget -qO- "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz"
        | tar -xJv
    - continue-on-error: true
      name: Run shellcheck
      run: find -name '*.sh' | xargs shellcheck-stable/shellcheck --format=gcc
name: Reusable - Shell script check
on:
  repository_dispatch:
    types: trigger-ga___reusable-shell-script-check.yml
permissions:
  contents: read
